# Generated by Django 4.2.7 on 2023-11-15 21:32

from django.db import migrations
def create_unique_uuid(apps, schema_editor):
    import uuid
    User = apps.get_model("users", "User")
    users_with_wrong_uuid = User.objects.all().difference(User.objects.distinct("uuid"))
    for u in users_with_wrong_uuid:
        u.uuid = uuid.uuid4()
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_uuid"),
    ]

    operations = [migrations.RunPython(create_unique_uuid, migrations.RunPython.noop)
    ]
