# Generated by Django 4.2.7 on 2024-01-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_userimage_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="FittedModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fitted_model", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
