# Generated by Django 4.2.7 on 2024-01-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_fittedmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fittedmodel",
            name="fitted_model",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
