# Generated by Django 4.2.7 on 2024-01-07 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_fittedmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLogs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "log_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recognized", "recognized"),
                            ("wrong password", "wrong password"),
                            ("unknown user", "unknown user"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
